# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'password_generator_v4.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QHBoxLayout,
    QLabel, QLineEdit, QMainWindow, QProgressBar,
    QPushButton, QSizePolicy, QSlider, QTextEdit,
    QVBoxLayout, QWidget)
import ui_addons_v2

class Ui_PasswordGenerator(object):
    def setupUi(self, PasswordGenerator):
        if not PasswordGenerator.objectName():
            PasswordGenerator.setObjectName(u"PasswordGenerator")
        PasswordGenerator.resize(420, 683)
        sizePolicy = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PasswordGenerator.sizePolicy().hasHeightForWidth())
        PasswordGenerator.setSizePolicy(sizePolicy)
        PasswordGenerator.setMinimumSize(QSize(420, 683))
        PasswordGenerator.setMaximumSize(QSize(420, 683))
        palette = QPalette()
        brush = QBrush(QColor(82, 173, 200, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        PasswordGenerator.setPalette(palette)
        PasswordGenerator.setAutoFillBackground(False)
        self.centralwidget = QWidget(PasswordGenerator)
        self.centralwidget.setObjectName(u"centralwidget")
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(-10, 0, 431, 41))
        palette1 = QPalette()
        brush1 = QBrush(QColor(85, 195, 158, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.widget.setPalette(palette1)
        self.widget.setAutoFillBackground(True)
        self.layoutWidget = QWidget(self.widget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(20, 10, 239, 27))
        self.horizontalLayout_5 = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.layoutWidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setPixmap(QPixmap(u":/newPrefix/hydro-power16.png"))
        self.label_2.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_5.addWidget(self.label_2)

        self.label = QLabel(self.layoutWidget)
        self.label.setObjectName(u"label")
        font = QFont()
        font.setFamilies([u"Univers LT Std 45 Light"])
        font.setPointSize(16)
        font.setBold(True)
        self.label.setFont(font)

        self.horizontalLayout_5.addWidget(self.label)

        self.v_line_2 = QFrame(self.centralwidget)
        self.v_line_2.setObjectName(u"v_line_2")
        self.v_line_2.setGeometry(QRect(240, 40, 21, 671))
        palette2 = QPalette()
        brush2 = QBrush(QColor(85, 255, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        brush3 = QBrush(QColor(127, 127, 127, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush3)
        brush4 = QBrush(QColor(123, 123, 123, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush4)
        brush5 = QBrush(QColor(93, 93, 93, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Midlight, brush5)
        brush6 = QBrush(QColor(0, 0, 0, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush6)
        palette2.setBrush(QPalette.Active, QPalette.Mid, brush4)
        brush7 = QBrush(QColor(0, 255, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush7)
        brush8 = QBrush(QColor(170, 255, 255, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.BrightText, brush8)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette2.setBrush(QPalette.Active, QPalette.Highlight, brush7)
        palette2.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette2.setBrush(QPalette.Active, QPalette.Link, brush6)
        brush9 = QBrush(QColor(83, 83, 83, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette2.setBrush(QPalette.Active, QPalette.AlternateBase, brush5)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
        brush10 = QBrush(QColor(140, 140, 140, 128))
        brush10.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush10)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Midlight, brush5)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.BrightText, brush8)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush5)
        palette2.setBrush(QPalette.Inactive, QPalette.Highlight, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.Link, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette2.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush5)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush10)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Light, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Midlight, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.BrightText, brush8)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.Link, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette2.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush10)
#endif
        self.v_line_2.setPalette(palette2)
        self.v_line_2.setStyleSheet(u"background-color: ")
        self.v_line_2.setFrameShape(QFrame.VLine)
        self.v_line_2.setFrameShadow(QFrame.Sunken)
        self.h_line_3 = QFrame(self.centralwidget)
        self.h_line_3.setObjectName(u"h_line_3")
        self.h_line_3.setGeometry(QRect(0, 30, 421, 21))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush4)
        palette3.setBrush(QPalette.Active, QPalette.Midlight, brush5)
        palette3.setBrush(QPalette.Active, QPalette.Dark, brush6)
        palette3.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush7)
        palette3.setBrush(QPalette.Active, QPalette.BrightText, brush8)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette3.setBrush(QPalette.Active, QPalette.Highlight, brush7)
        palette3.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette3.setBrush(QPalette.Active, QPalette.Link, brush6)
        palette3.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette3.setBrush(QPalette.Active, QPalette.AlternateBase, brush5)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush10)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.Light, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Midlight, brush5)
        palette3.setBrush(QPalette.Inactive, QPalette.Dark, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush7)
        palette3.setBrush(QPalette.Inactive, QPalette.BrightText, brush8)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush7)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush5)
        palette3.setBrush(QPalette.Inactive, QPalette.Highlight, brush7)
        palette3.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.Link, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette3.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush5)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush10)
#endif
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Light, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Midlight, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.Dark, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.BrightText, brush8)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.Link, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette3.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush10)
#endif
        self.h_line_3.setPalette(palette3)
        self.h_line_3.setFrameShape(QFrame.HLine)
        self.h_line_3.setFrameShadow(QFrame.Sunken)
        self.passwords_output = QTextEdit(self.centralwidget)
        self.passwords_output.setObjectName(u"passwords_output")
        self.passwords_output.setGeometry(QRect(0, 270, 231, 371))
        palette4 = QPalette()
        brush11 = QBrush(QColor(56, 124, 163, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush11)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush11)
        self.passwords_output.setPalette(palette4)
        font1 = QFont()
        font1.setFamilies([u"Univers LT Std"])
        font1.setPointSize(11)
        font1.setBold(False)
        self.passwords_output.setFont(font1)
        self.passwords_output.setFrameShape(QFrame.StyledPanel)
        self.passwords_output.setFrameShadow(QFrame.Raised)
        self.passwords_output.setLineWidth(8)
        self.passwords_output.setMidLineWidth(4)
        self.passwords_output.setLineWrapColumnOrWidth(0)
        self.passwords_output.setReadOnly(True)
        self.generate_button = QPushButton(self.centralwidget)
        self.generate_button.setObjectName(u"generate_button")
        self.generate_button.setEnabled(True)
        self.generate_button.setGeometry(QRect(60, 230, 131, 31))
        self.generate_button.setMinimumSize(QSize(131, 31))
        self.generate_button.setMaximumSize(QSize(131, 31))
        font2 = QFont()
        font2.setFamilies([u"Univers LT Std"])
        font2.setPointSize(14)
        font2.setBold(True)
        font2.setKerning(True)
        font2.setStyleStrategy(QFont.PreferDefault)
        self.generate_button.setFont(font2)
        self.generate_button.setMouseTracking(True)
        self.generate_button.setAcceptDrops(False)
        self.generate_button.setLayoutDirection(Qt.RightToLeft)
        self.generate_button.setAutoFillBackground(False)
        self.generate_button.setStyleSheet(u"background-color: #55c39e;\n"
"padding: 5px;\n"
"image: url(:/newPrefix/hydro-power16.png);\n"
"image-position: left;")
        self.generate_button.setCheckable(False)
        self.widget_2 = QWidget(self.centralwidget)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(250, 40, 171, 41))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.widget_2.setPalette(palette5)
        self.widget_2.setAutoFillBackground(True)
        self.layoutWidget1 = QWidget(self.widget_2)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(20, 0, 111, 41))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_6 = QLabel(self.layoutWidget1)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setPixmap(QPixmap(u":/newPrefix/puzzle.png"))
        self.label_6.setAlignment(Qt.AlignCenter)

        self.horizontalLayout.addWidget(self.label_6)

        self.label_5 = QLabel(self.layoutWidget1)
        self.label_5.setObjectName(u"label_5")
        font3 = QFont()
        font3.setFamilies([u"Univers LT Std 45 Light"])
        font3.setPointSize(12)
        font3.setBold(True)
        self.label_5.setFont(font3)

        self.horizontalLayout.addWidget(self.label_5)

        self.h_line_4 = QFrame(self.centralwidget)
        self.h_line_4.setObjectName(u"h_line_4")
        self.h_line_4.setGeometry(QRect(-10, 260, 261, 21))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette6.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette6.setBrush(QPalette.Active, QPalette.Light, brush4)
        palette6.setBrush(QPalette.Active, QPalette.Midlight, brush5)
        palette6.setBrush(QPalette.Active, QPalette.Dark, brush6)
        palette6.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush7)
        palette6.setBrush(QPalette.Active, QPalette.BrightText, brush8)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette6.setBrush(QPalette.Active, QPalette.Highlight, brush7)
        palette6.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette6.setBrush(QPalette.Active, QPalette.Link, brush6)
        palette6.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette6.setBrush(QPalette.Active, QPalette.AlternateBase, brush5)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Active, QPalette.PlaceholderText, brush10)
#endif
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette6.setBrush(QPalette.Inactive, QPalette.Light, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.Midlight, brush5)
        palette6.setBrush(QPalette.Inactive, QPalette.Dark, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush7)
        palette6.setBrush(QPalette.Inactive, QPalette.BrightText, brush8)
        palette6.setBrush(QPalette.Inactive, QPalette.ButtonText, brush7)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush5)
        palette6.setBrush(QPalette.Inactive, QPalette.Highlight, brush7)
        palette6.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.Link, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette6.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush5)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush10)
#endif
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette6.setBrush(QPalette.Disabled, QPalette.Light, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Midlight, brush5)
        palette6.setBrush(QPalette.Disabled, QPalette.Dark, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.BrightText, brush8)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette6.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.Link, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette6.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush5)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush10)
#endif
        self.h_line_4.setPalette(palette6)
        self.h_line_4.setFrameShape(QFrame.HLine)
        self.h_line_4.setFrameShadow(QFrame.Sunken)
        self.h_line_5 = QFrame(self.centralwidget)
        self.h_line_5.setObjectName(u"h_line_5")
        self.h_line_5.setGeometry(QRect(-10, 630, 261, 21))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette7.setBrush(QPalette.Active, QPalette.Light, brush4)
        palette7.setBrush(QPalette.Active, QPalette.Midlight, brush5)
        palette7.setBrush(QPalette.Active, QPalette.Dark, brush6)
        palette7.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette7.setBrush(QPalette.Active, QPalette.Text, brush7)
        palette7.setBrush(QPalette.Active, QPalette.BrightText, brush8)
        palette7.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette7.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette7.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette7.setBrush(QPalette.Active, QPalette.Highlight, brush7)
        palette7.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette7.setBrush(QPalette.Active, QPalette.Link, brush6)
        palette7.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette7.setBrush(QPalette.Active, QPalette.AlternateBase, brush5)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Active, QPalette.PlaceholderText, brush10)
#endif
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette7.setBrush(QPalette.Inactive, QPalette.Light, brush4)
        palette7.setBrush(QPalette.Inactive, QPalette.Midlight, brush5)
        palette7.setBrush(QPalette.Inactive, QPalette.Dark, brush6)
        palette7.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette7.setBrush(QPalette.Inactive, QPalette.Text, brush7)
        palette7.setBrush(QPalette.Inactive, QPalette.BrightText, brush8)
        palette7.setBrush(QPalette.Inactive, QPalette.ButtonText, brush7)
        palette7.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette7.setBrush(QPalette.Inactive, QPalette.Window, brush5)
        palette7.setBrush(QPalette.Inactive, QPalette.Highlight, brush7)
        palette7.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush6)
        palette7.setBrush(QPalette.Inactive, QPalette.Link, brush6)
        palette7.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette7.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush5)
        palette7.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette7.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush10)
#endif
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette7.setBrush(QPalette.Disabled, QPalette.Light, brush4)
        palette7.setBrush(QPalette.Disabled, QPalette.Midlight, brush5)
        palette7.setBrush(QPalette.Disabled, QPalette.Dark, brush6)
        palette7.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette7.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette7.setBrush(QPalette.Disabled, QPalette.BrightText, brush8)
        palette7.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette7.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette7.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        palette7.setBrush(QPalette.Disabled, QPalette.Link, brush6)
        palette7.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette7.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush5)
        palette7.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette7.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush10)
#endif
        self.h_line_5.setPalette(palette7)
        self.h_line_5.setFrameShape(QFrame.HLine)
        self.h_line_5.setFrameShadow(QFrame.Sunken)
        self.h_line_6 = QFrame(self.centralwidget)
        self.h_line_6.setObjectName(u"h_line_6")
        self.h_line_6.setGeometry(QRect(250, 70, 261, 21))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette8.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette8.setBrush(QPalette.Active, QPalette.Light, brush4)
        palette8.setBrush(QPalette.Active, QPalette.Midlight, brush5)
        palette8.setBrush(QPalette.Active, QPalette.Dark, brush6)
        palette8.setBrush(QPalette.Active, QPalette.Mid, brush4)
        palette8.setBrush(QPalette.Active, QPalette.Text, brush7)
        palette8.setBrush(QPalette.Active, QPalette.BrightText, brush8)
        palette8.setBrush(QPalette.Active, QPalette.ButtonText, brush7)
        palette8.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette8.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette8.setBrush(QPalette.Active, QPalette.Highlight, brush7)
        palette8.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette8.setBrush(QPalette.Active, QPalette.Link, brush6)
        palette8.setBrush(QPalette.Active, QPalette.LinkVisited, brush9)
        palette8.setBrush(QPalette.Active, QPalette.AlternateBase, brush5)
        palette8.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette8.setBrush(QPalette.Active, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Active, QPalette.PlaceholderText, brush10)
#endif
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette8.setBrush(QPalette.Inactive, QPalette.Light, brush4)
        palette8.setBrush(QPalette.Inactive, QPalette.Midlight, brush5)
        palette8.setBrush(QPalette.Inactive, QPalette.Dark, brush6)
        palette8.setBrush(QPalette.Inactive, QPalette.Mid, brush4)
        palette8.setBrush(QPalette.Inactive, QPalette.Text, brush7)
        palette8.setBrush(QPalette.Inactive, QPalette.BrightText, brush8)
        palette8.setBrush(QPalette.Inactive, QPalette.ButtonText, brush7)
        palette8.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette8.setBrush(QPalette.Inactive, QPalette.Window, brush5)
        palette8.setBrush(QPalette.Inactive, QPalette.Highlight, brush7)
        palette8.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush6)
        palette8.setBrush(QPalette.Inactive, QPalette.Link, brush6)
        palette8.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush9)
        palette8.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush5)
        palette8.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette8.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush10)
#endif
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette8.setBrush(QPalette.Disabled, QPalette.Light, brush4)
        palette8.setBrush(QPalette.Disabled, QPalette.Midlight, brush5)
        palette8.setBrush(QPalette.Disabled, QPalette.Dark, brush6)
        palette8.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        palette8.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette8.setBrush(QPalette.Disabled, QPalette.BrightText, brush8)
        palette8.setBrush(QPalette.Disabled, QPalette.ButtonText, brush6)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette8.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette8.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        palette8.setBrush(QPalette.Disabled, QPalette.Link, brush6)
        palette8.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush9)
        palette8.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush5)
        palette8.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette8.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush5)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush10)
#endif
        self.h_line_6.setPalette(palette8)
        self.h_line_6.setFrameShape(QFrame.HLine)
        self.h_line_6.setFrameShadow(QFrame.Sunken)
        self.layoutWidget2 = QWidget(self.centralwidget)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(260, 90, 151, 201))
        self.verticalLayout = QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.numbers_checkbox = QCheckBox(self.layoutWidget2)
        self.numbers_checkbox.setObjectName(u"numbers_checkbox")
        font4 = QFont()
        font4.setFamilies([u"Univers LT Std"])
        font4.setPointSize(11)
        font4.setBold(True)
        self.numbers_checkbox.setFont(font4)
        self.numbers_checkbox.setChecked(True)

        self.verticalLayout.addWidget(self.numbers_checkbox)

        self.symbols_checkbox = QCheckBox(self.layoutWidget2)
        self.symbols_checkbox.setObjectName(u"symbols_checkbox")
        self.symbols_checkbox.setFont(font4)
        self.symbols_checkbox.setChecked(True)

        self.verticalLayout.addWidget(self.symbols_checkbox)

        self.lowercase_checkbox = QCheckBox(self.layoutWidget2)
        self.lowercase_checkbox.setObjectName(u"lowercase_checkbox")
        self.lowercase_checkbox.setFont(font4)
        self.lowercase_checkbox.setChecked(True)

        self.verticalLayout.addWidget(self.lowercase_checkbox)

        self.uppercase_checkbox = QCheckBox(self.layoutWidget2)
        self.uppercase_checkbox.setObjectName(u"uppercase_checkbox")
        self.uppercase_checkbox.setFont(font4)
        self.uppercase_checkbox.setChecked(True)
        self.uppercase_checkbox.setTristate(False)

        self.verticalLayout.addWidget(self.uppercase_checkbox)

        self.layoutWidget3 = QWidget(self.centralwidget)
        self.layoutWidget3.setObjectName(u"layoutWidget3")
        self.layoutWidget3.setGeometry(QRect(10, 60, 234, 161))
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.label_3 = QLabel(self.layoutWidget3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFont(font3)

        self.horizontalLayout_2.addWidget(self.label_3)

        self.amount_input = QLineEdit(self.layoutWidget3)
        self.amount_input.setObjectName(u"amount_input")
        self.amount_input.setMinimumSize(QSize(41, 19))
        self.amount_input.setMaximumSize(QSize(41, 19))

        self.horizontalLayout_2.addWidget(self.amount_input)


        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.amount_input_slider = QSlider(self.layoutWidget3)
        self.amount_input_slider.setObjectName(u"amount_input_slider")
        self.amount_input_slider.setMinimum(2)
        self.amount_input_slider.setMaximum(15)
        self.amount_input_slider.setPageStep(2)
        self.amount_input_slider.setSliderPosition(2)
        self.amount_input_slider.setOrientation(Qt.Horizontal)

        self.verticalLayout_2.addWidget(self.amount_input_slider)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.label_4 = QLabel(self.layoutWidget3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setFont(font3)

        self.horizontalLayout_3.addWidget(self.label_4)

        self.length_input = QLineEdit(self.layoutWidget3)
        self.length_input.setObjectName(u"length_input")
        self.length_input.setMinimumSize(QSize(41, 19))
        self.length_input.setMaximumSize(QSize(41, 19))

        self.horizontalLayout_3.addWidget(self.length_input)


        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.length_input_slider = QSlider(self.layoutWidget3)
        self.length_input_slider.setObjectName(u"length_input_slider")
        self.length_input_slider.setMinimum(6)
        self.length_input_slider.setMaximum(20)
        self.length_input_slider.setPageStep(2)
        self.length_input_slider.setSliderPosition(6)
        self.length_input_slider.setOrientation(Qt.Horizontal)

        self.verticalLayout_2.addWidget(self.length_input_slider)

        self.layoutWidget4 = QWidget(self.centralwidget)
        self.layoutWidget4.setObjectName(u"layoutWidget4")
        self.layoutWidget4.setGeometry(QRect(70, 642, 181, 41))
        self.horizontalLayout_4 = QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.clear_button = QPushButton(self.layoutWidget4)
        self.clear_button.setObjectName(u"clear_button")
        self.clear_button.setEnabled(True)
        self.clear_button.setMinimumSize(QSize(81, 31))
        self.clear_button.setMaximumSize(QSize(81, 31))
        self.clear_button.setFont(font2)
        self.clear_button.setMouseTracking(True)
        self.clear_button.setAcceptDrops(False)
        self.clear_button.setLayoutDirection(Qt.RightToLeft)
        self.clear_button.setAutoFillBackground(False)
        self.clear_button.setStyleSheet(u"background-color: #55c39e;\n"
"padding: 5px;\n"
"image: url(:/newPrefix/trash.png);\n"
"image-position: left;")
        self.clear_button.setCheckable(False)

        self.horizontalLayout_4.addWidget(self.clear_button)

        self.exit_button = QPushButton(self.layoutWidget4)
        self.exit_button.setObjectName(u"exit_button")
        self.exit_button.setEnabled(True)
        self.exit_button.setMinimumSize(QSize(81, 31))
        self.exit_button.setMaximumSize(QSize(81, 31))
        self.exit_button.setFont(font2)
        self.exit_button.setMouseTracking(True)
        self.exit_button.setAcceptDrops(False)
        self.exit_button.setLayoutDirection(Qt.RightToLeft)
        self.exit_button.setAutoFillBackground(False)
        self.exit_button.setStyleSheet(u"background-color: #55c39e;\n"
"padding: 5px;\n"
"image: url(:/newPrefix/power-off.png);\n"
"image-position: left;")
        self.exit_button.setCheckable(False)

        self.horizontalLayout_4.addWidget(self.exit_button)

        self.Security_rating = QProgressBar(self.centralwidget)
        self.Security_rating.setObjectName(u"Security_rating")
        self.Security_rating.setGeometry(QRect(230, 270, 21, 371))
        self.Security_rating.setMaximum(100)
        self.Security_rating.setValue(0)
        self.Security_rating.setOrientation(Qt.Vertical)
        self.Security_rating.setInvertedAppearance(False)
        self.Rating_label = QLabel(self.centralwidget)
        self.Rating_label.setObjectName(u"Rating_label")
        self.Rating_label.setGeometry(QRect(230, 240, 21, 31))
        self.Rating_label.setPixmap(QPixmap(u":/newPrefix/security_rating.png"))
        PasswordGenerator.setCentralWidget(self.centralwidget)

        self.retranslateUi(PasswordGenerator)

        QMetaObject.connectSlotsByName(PasswordGenerator)
    # setupUi

    def retranslateUi(self, PasswordGenerator):
        PasswordGenerator.setWindowTitle(QCoreApplication.translate("PasswordGenerator", u"MainWindow", None))
        self.label_2.setText("")
        self.label.setText(QCoreApplication.translate("PasswordGenerator", u"Password Generator", None))
        self.generate_button.setText(QCoreApplication.translate("PasswordGenerator", u"   Generate", None))
        self.label_6.setText("")
        self.label_5.setText(QCoreApplication.translate("PasswordGenerator", u"Settings", None))
        self.numbers_checkbox.setText(QCoreApplication.translate("PasswordGenerator", u"Numbers", None))
        self.symbols_checkbox.setText(QCoreApplication.translate("PasswordGenerator", u"Special symbols", None))
        self.lowercase_checkbox.setText(QCoreApplication.translate("PasswordGenerator", u"Lowercase letters", None))
        self.uppercase_checkbox.setText(QCoreApplication.translate("PasswordGenerator", u"Uppercase letters", None))
        self.label_3.setText(QCoreApplication.translate("PasswordGenerator", u"Amount to generate:", None))
        self.label_4.setText(QCoreApplication.translate("PasswordGenerator", u"Length per password:", None))
        self.clear_button.setText(QCoreApplication.translate("PasswordGenerator", u"    Clear", None))
        self.exit_button.setText(QCoreApplication.translate("PasswordGenerator", u"    Quit", None))
        self.Rating_label.setText("")
    # retranslateUi
