# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'password_generator_v2.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QSlider, QTextEdit, QWidget)

class Ui_PasswordGenerator(object):
    def setupUi(self, PasswordGenerator):
        if not PasswordGenerator.objectName():
            PasswordGenerator.setObjectName(u"PasswordGenerator")
        PasswordGenerator.resize(423, 555)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PasswordGenerator.sizePolicy().hasHeightForWidth())
        PasswordGenerator.setSizePolicy(sizePolicy)
        PasswordGenerator.setMinimumSize(QSize(387, 555))
        PasswordGenerator.setMaximumSize(QSize(500, 1000))
        palette = QPalette()
        brush = QBrush(QColor(85, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(127, 127, 127, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(123, 123, 123, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(93, 93, 93, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(0, 0, 0, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush2)
        brush5 = QBrush(QColor(0, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush5)
        brush6 = QBrush(QColor(170, 255, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette.setBrush(QPalette.Active, QPalette.Highlight, brush5)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush4)
        palette.setBrush(QPalette.Active, QPalette.Link, brush4)
        brush7 = QBrush(QColor(83, 83, 83, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.LinkVisited, brush7)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush3)
        brush8 = QBrush(QColor(140, 140, 140, 128))
        brush8.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Link, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Link, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        PasswordGenerator.setPalette(palette)
        PasswordGenerator.setAnimated(True)
        self.centralwidget = QWidget(PasswordGenerator)
        self.centralwidget.setObjectName(u"centralwidget")
        self.amount_input_slider = QSlider(self.centralwidget)
        self.amount_input_slider.setObjectName(u"amount_input_slider")
        self.amount_input_slider.setGeometry(QRect(90, 40, 160, 22))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Highlight, brush5)
        palette1.setBrush(QPalette.Active, QPalette.HighlightedText, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Link, brush4)
        palette1.setBrush(QPalette.Active, QPalette.LinkVisited, brush7)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush5)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Highlight, brush5)
        palette1.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Link, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Link, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush7)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.amount_input_slider.setPalette(palette1)
        self.amount_input_slider.setMinimum(1)
        self.amount_input_slider.setMaximum(25)
        self.amount_input_slider.setOrientation(Qt.Horizontal)
        self.length_input_slider = QSlider(self.centralwidget)
        self.length_input_slider.setObjectName(u"length_input_slider")
        self.length_input_slider.setGeometry(QRect(90, 110, 160, 22))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette2.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Highlight, brush5)
        palette2.setBrush(QPalette.Active, QPalette.HighlightedText, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Link, brush4)
        palette2.setBrush(QPalette.Active, QPalette.LinkVisited, brush7)
        palette2.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush5)
        palette2.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Highlight, brush5)
        palette2.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Link, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Link, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush7)
        palette2.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.length_input_slider.setPalette(palette2)
        self.length_input_slider.setMinimum(6)
        self.length_input_slider.setMaximum(25)
        self.length_input_slider.setOrientation(Qt.Horizontal)
        self.amount_label = QLabel(self.centralwidget)
        self.amount_label.setObjectName(u"amount_label")
        self.amount_label.setGeometry(QRect(10, 20, 61, 41))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette3.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette3.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette3.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette3.setBrush(QPalette.Active, QPalette.Highlight, brush5)
        palette3.setBrush(QPalette.Active, QPalette.HighlightedText, brush4)
        palette3.setBrush(QPalette.Active, QPalette.Link, brush4)
        palette3.setBrush(QPalette.Active, QPalette.LinkVisited, brush7)
        palette3.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush5)
        palette3.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.Highlight, brush5)
        palette3.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Link, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush7)
        palette3.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Link, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush7)
        palette3.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.amount_label.setPalette(palette3)
        font = QFont()
        font.setFamilies([u"Candara"])
        font.setPointSize(10)
        font.setBold(True)
        self.amount_label.setFont(font)
        self.length_label = QLabel(self.centralwidget)
        self.length_label.setObjectName(u"length_label")
        self.length_label.setGeometry(QRect(10, 90, 61, 51))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette4.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette4.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette4.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette4.setBrush(QPalette.Active, QPalette.Highlight, brush5)
        palette4.setBrush(QPalette.Active, QPalette.HighlightedText, brush4)
        palette4.setBrush(QPalette.Active, QPalette.Link, brush4)
        palette4.setBrush(QPalette.Active, QPalette.LinkVisited, brush7)
        palette4.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette4.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette4.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush5)
        palette4.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette4.setBrush(QPalette.Inactive, QPalette.Highlight, brush5)
        palette4.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush4)
        palette4.setBrush(QPalette.Inactive, QPalette.Link, brush4)
        palette4.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush7)
        palette4.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Link, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush7)
        palette4.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.length_label.setPalette(palette4)
        font1 = QFont()
        font1.setFamilies([u"Candara"])
        font1.setPointSize(11)
        font1.setBold(True)
        font1.setStyleStrategy(QFont.PreferAntialias)
        self.length_label.setFont(font1)
        self.amount_input = QLineEdit(self.centralwidget)
        self.amount_input.setObjectName(u"amount_input")
        self.amount_input.setGeometry(QRect(140, 10, 41, 21))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette5.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette5.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette5.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette5.setBrush(QPalette.Active, QPalette.Highlight, brush5)
        palette5.setBrush(QPalette.Active, QPalette.HighlightedText, brush4)
        palette5.setBrush(QPalette.Active, QPalette.Link, brush4)
        palette5.setBrush(QPalette.Active, QPalette.LinkVisited, brush7)
        palette5.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette5.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette5.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush5)
        palette5.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette5.setBrush(QPalette.Inactive, QPalette.Highlight, brush5)
        palette5.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush4)
        palette5.setBrush(QPalette.Inactive, QPalette.Link, brush4)
        palette5.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush7)
        palette5.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette5.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette5.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.Link, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush7)
        palette5.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush3)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.amount_input.setPalette(palette5)
        self.length_input = QLineEdit(self.centralwidget)
        self.length_input.setObjectName(u"length_input")
        self.length_input.setGeometry(QRect(140, 80, 41, 21))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette6.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette6.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette6.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette6.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette6.setBrush(QPalette.Active, QPalette.Highlight, brush5)
        palette6.setBrush(QPalette.Active, QPalette.HighlightedText, brush4)
        palette6.setBrush(QPalette.Active, QPalette.Link, brush4)
        palette6.setBrush(QPalette.Active, QPalette.LinkVisited, brush7)
        palette6.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette6.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush5)
        palette6.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette6.setBrush(QPalette.Inactive, QPalette.Highlight, brush5)
        palette6.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.Link, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush7)
        palette6.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette6.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette6.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.Link, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush7)
        palette6.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush3)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.length_input.setPalette(palette6)
        self.h_line_1 = QFrame(self.centralwidget)
        self.h_line_1.setObjectName(u"h_line_1")
        self.h_line_1.setGeometry(QRect(0, 60, 291, 21))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette7.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette7.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette7.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette7.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette7.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette7.setBrush(QPalette.Active, QPalette.Highlight, brush5)
        palette7.setBrush(QPalette.Active, QPalette.HighlightedText, brush4)
        palette7.setBrush(QPalette.Active, QPalette.Link, brush4)
        palette7.setBrush(QPalette.Active, QPalette.LinkVisited, brush7)
        palette7.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette7.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette7.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Text, brush5)
        palette7.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette7.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette7.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette7.setBrush(QPalette.Inactive, QPalette.Highlight, brush5)
        palette7.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush4)
        palette7.setBrush(QPalette.Inactive, QPalette.Link, brush4)
        palette7.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush7)
        palette7.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette7.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette7.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette7.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette7.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette7.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette7.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette7.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette7.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush4)
        palette7.setBrush(QPalette.Disabled, QPalette.Link, brush4)
        palette7.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush7)
        palette7.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush3)
        palette7.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette7.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.h_line_1.setPalette(palette7)
        self.h_line_1.setFrameShape(QFrame.HLine)
        self.h_line_1.setFrameShadow(QFrame.Sunken)
        self.generate_button = QPushButton(self.centralwidget)
        self.generate_button.setObjectName(u"generate_button")
        self.generate_button.setGeometry(QRect(90, 160, 111, 41))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette8.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette8.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette8.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette8.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette8.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette8.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette8.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette8.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette8.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette8.setBrush(QPalette.Active, QPalette.Highlight, brush5)
        palette8.setBrush(QPalette.Active, QPalette.HighlightedText, brush4)
        palette8.setBrush(QPalette.Active, QPalette.Link, brush4)
        palette8.setBrush(QPalette.Active, QPalette.LinkVisited, brush7)
        palette8.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette8.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette8.setBrush(QPalette.Active, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette8.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette8.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.Text, brush5)
        palette8.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette8.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette8.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette8.setBrush(QPalette.Inactive, QPalette.Highlight, brush5)
        palette8.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush4)
        palette8.setBrush(QPalette.Inactive, QPalette.Link, brush4)
        palette8.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush7)
        palette8.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette8.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette8.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette8.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette8.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette8.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette8.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette8.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette8.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette8.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush4)
        palette8.setBrush(QPalette.Disabled, QPalette.Link, brush4)
        palette8.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush7)
        palette8.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush3)
        palette8.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette8.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.generate_button.setPalette(palette8)
        font2 = QFont()
        font2.setFamilies([u"Candara"])
        font2.setPointSize(15)
        font2.setBold(True)
        font2.setStyleStrategy(QFont.PreferAntialias)
        self.generate_button.setFont(font2)
        self.generate_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.generate_button.setAutoFillBackground(False)
        self.generate_button.setFlat(False)
        self.h_line_2 = QFrame(self.centralwidget)
        self.h_line_2.setObjectName(u"h_line_2")
        self.h_line_2.setGeometry(QRect(0, 140, 291, 21))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette9.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette9.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette9.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette9.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette9.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette9.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette9.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette9.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette9.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette9.setBrush(QPalette.Active, QPalette.Highlight, brush5)
        palette9.setBrush(QPalette.Active, QPalette.HighlightedText, brush4)
        palette9.setBrush(QPalette.Active, QPalette.Link, brush4)
        palette9.setBrush(QPalette.Active, QPalette.LinkVisited, brush7)
        palette9.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette9.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette9.setBrush(QPalette.Active, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette9.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette9.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.Text, brush5)
        palette9.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette9.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette9.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette9.setBrush(QPalette.Inactive, QPalette.Highlight, brush5)
        palette9.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush4)
        palette9.setBrush(QPalette.Inactive, QPalette.Link, brush4)
        palette9.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush7)
        palette9.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette9.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette9.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette9.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette9.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette9.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette9.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette9.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette9.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette9.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush4)
        palette9.setBrush(QPalette.Disabled, QPalette.Link, brush4)
        palette9.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush7)
        palette9.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush3)
        palette9.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette9.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.h_line_2.setPalette(palette9)
        self.h_line_2.setFrameShape(QFrame.HLine)
        self.h_line_2.setFrameShadow(QFrame.Sunken)
        self.passwords_output = QTextEdit(self.centralwidget)
        self.passwords_output.setObjectName(u"passwords_output")
        self.passwords_output.setGeometry(QRect(0, 210, 291, 301))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette10.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette10.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette10.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette10.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette10.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette10.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette10.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette10.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette10.setBrush(QPalette.Active, QPalette.Highlight, brush5)
        palette10.setBrush(QPalette.Active, QPalette.HighlightedText, brush4)
        palette10.setBrush(QPalette.Active, QPalette.Link, brush4)
        palette10.setBrush(QPalette.Active, QPalette.LinkVisited, brush7)
        palette10.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette10.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette10.setBrush(QPalette.Active, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette10.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette10.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.Text, brush5)
        palette10.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette10.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette10.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette10.setBrush(QPalette.Inactive, QPalette.Highlight, brush5)
        palette10.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush4)
        palette10.setBrush(QPalette.Inactive, QPalette.Link, brush4)
        palette10.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush7)
        palette10.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette10.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette10.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette10.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette10.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette10.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush4)
        palette10.setBrush(QPalette.Disabled, QPalette.Link, brush4)
        palette10.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush7)
        palette10.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette10.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.passwords_output.setPalette(palette10)
        font3 = QFont()
        font3.setPointSize(10)
        self.passwords_output.setFont(font3)
        self.passwords_output.setReadOnly(True)
        self.exit_button = QPushButton(self.centralwidget)
        self.exit_button.setObjectName(u"exit_button")
        self.exit_button.setGeometry(QRect(210, 520, 81, 31))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette11.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette11.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette11.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette11.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette11.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette11.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette11.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette11.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette11.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette11.setBrush(QPalette.Active, QPalette.Highlight, brush5)
        palette11.setBrush(QPalette.Active, QPalette.HighlightedText, brush4)
        palette11.setBrush(QPalette.Active, QPalette.Link, brush4)
        palette11.setBrush(QPalette.Active, QPalette.LinkVisited, brush7)
        palette11.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette11.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette11.setBrush(QPalette.Active, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette11.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette11.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette11.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette11.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette11.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette11.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette11.setBrush(QPalette.Inactive, QPalette.Text, brush5)
        palette11.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette11.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette11.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette11.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette11.setBrush(QPalette.Inactive, QPalette.Highlight, brush5)
        palette11.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush4)
        palette11.setBrush(QPalette.Inactive, QPalette.Link, brush4)
        palette11.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush7)
        palette11.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette11.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette11.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette11.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette11.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette11.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette11.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette11.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette11.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette11.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette11.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette11.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette11.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette11.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush4)
        palette11.setBrush(QPalette.Disabled, QPalette.Link, brush4)
        palette11.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush7)
        palette11.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush3)
        palette11.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette11.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette11.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.exit_button.setPalette(palette11)
        self.clear_button = QPushButton(self.centralwidget)
        self.clear_button.setObjectName(u"clear_button")
        self.clear_button.setGeometry(QRect(130, 520, 81, 31))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette12.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette12.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette12.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette12.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette12.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette12.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette12.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette12.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette12.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette12.setBrush(QPalette.Active, QPalette.Highlight, brush5)
        palette12.setBrush(QPalette.Active, QPalette.HighlightedText, brush4)
        palette12.setBrush(QPalette.Active, QPalette.Link, brush4)
        palette12.setBrush(QPalette.Active, QPalette.LinkVisited, brush7)
        palette12.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette12.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette12.setBrush(QPalette.Active, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette12.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette12.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette12.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette12.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette12.setBrush(QPalette.Inactive, QPalette.Text, brush5)
        palette12.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette12.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette12.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette12.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette12.setBrush(QPalette.Inactive, QPalette.Highlight, brush5)
        palette12.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush4)
        palette12.setBrush(QPalette.Inactive, QPalette.Link, brush4)
        palette12.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush7)
        palette12.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette12.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette12.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette12.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette12.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette12.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette12.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette12.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette12.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette12.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette12.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette12.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette12.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette12.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette12.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush4)
        palette12.setBrush(QPalette.Disabled, QPalette.Link, brush4)
        palette12.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush7)
        palette12.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush3)
        palette12.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette12.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.clear_button.setPalette(palette12)
        self.v_line_1 = QFrame(self.centralwidget)
        self.v_line_1.setObjectName(u"v_line_1")
        self.v_line_1.setGeometry(QRect(280, 0, 20, 551))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette13.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette13.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette13.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette13.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette13.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette13.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette13.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette13.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette13.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette13.setBrush(QPalette.Active, QPalette.Highlight, brush5)
        palette13.setBrush(QPalette.Active, QPalette.HighlightedText, brush4)
        palette13.setBrush(QPalette.Active, QPalette.Link, brush4)
        palette13.setBrush(QPalette.Active, QPalette.LinkVisited, brush7)
        palette13.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette13.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette13.setBrush(QPalette.Active, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette13.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette13.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette13.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.Text, brush5)
        palette13.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette13.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette13.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette13.setBrush(QPalette.Inactive, QPalette.Highlight, brush5)
        palette13.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush4)
        palette13.setBrush(QPalette.Inactive, QPalette.Link, brush4)
        palette13.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush7)
        palette13.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette13.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette13.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette13.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette13.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette13.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette13.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette13.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette13.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette13.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette13.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette13.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush4)
        palette13.setBrush(QPalette.Disabled, QPalette.Link, brush4)
        palette13.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush7)
        palette13.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush3)
        palette13.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette13.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.v_line_1.setPalette(palette13)
        self.v_line_1.setFrameShape(QFrame.VLine)
        self.v_line_1.setFrameShadow(QFrame.Sunken)
        self.addons_label = QLabel(self.centralwidget)
        self.addons_label.setObjectName(u"addons_label")
        self.addons_label.setGeometry(QRect(320, 10, 51, 41))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette14.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette14.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette14.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette14.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette14.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette14.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette14.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette14.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette14.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette14.setBrush(QPalette.Active, QPalette.Highlight, brush5)
        palette14.setBrush(QPalette.Active, QPalette.HighlightedText, brush4)
        palette14.setBrush(QPalette.Active, QPalette.Link, brush4)
        palette14.setBrush(QPalette.Active, QPalette.LinkVisited, brush7)
        palette14.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette14.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette14.setBrush(QPalette.Active, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette14.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette14.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.Text, brush5)
        palette14.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette14.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette14.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette14.setBrush(QPalette.Inactive, QPalette.Highlight, brush5)
        palette14.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush4)
        palette14.setBrush(QPalette.Inactive, QPalette.Link, brush4)
        palette14.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush7)
        palette14.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette14.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette14.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette14.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette14.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette14.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette14.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette14.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette14.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette14.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette14.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette14.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette14.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush4)
        palette14.setBrush(QPalette.Disabled, QPalette.Link, brush4)
        palette14.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush7)
        palette14.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush3)
        palette14.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette14.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.addons_label.setPalette(palette14)
        self.no_numbers_checkbox = QCheckBox(self.centralwidget)
        self.no_numbers_checkbox.setObjectName(u"no_numbers_checkbox")
        self.no_numbers_checkbox.setGeometry(QRect(310, 60, 91, 20))
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette15.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette15.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette15.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette15.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette15.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette15.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette15.setBrush(QPalette.Active, QPalette.Highlight, brush5)
        palette15.setBrush(QPalette.Active, QPalette.HighlightedText, brush4)
        palette15.setBrush(QPalette.Active, QPalette.Link, brush4)
        palette15.setBrush(QPalette.Active, QPalette.LinkVisited, brush7)
        palette15.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette15.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette15.setBrush(QPalette.Active, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette15.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette15.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette15.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette15.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Text, brush5)
        palette15.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette15.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette15.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette15.setBrush(QPalette.Inactive, QPalette.Highlight, brush5)
        palette15.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush4)
        palette15.setBrush(QPalette.Inactive, QPalette.Link, brush4)
        palette15.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush7)
        palette15.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette15.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette15.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette15.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette15.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette15.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette15.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette15.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette15.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette15.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette15.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette15.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette15.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush4)
        palette15.setBrush(QPalette.Disabled, QPalette.Link, brush4)
        palette15.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush7)
        palette15.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush3)
        palette15.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette15.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.no_numbers_checkbox.setPalette(palette15)
        font4 = QFont()
        font4.setBold(False)
        font4.setUnderline(False)
        font4.setStrikeOut(False)
        font4.setKerning(True)
        font4.setStyleStrategy(QFont.PreferAntialias)
        self.no_numbers_checkbox.setFont(font4)
        self.no_symbols_checkbox = QCheckBox(self.centralwidget)
        self.no_symbols_checkbox.setObjectName(u"no_symbols_checkbox")
        self.no_symbols_checkbox.setGeometry(QRect(310, 90, 91, 20))
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette16.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette16.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette16.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette16.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette16.setBrush(QPalette.Active, QPalette.Mid, brush2)
        palette16.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette16.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette16.setBrush(QPalette.Active, QPalette.ButtonText, brush5)
        palette16.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette16.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette16.setBrush(QPalette.Active, QPalette.Highlight, brush5)
        palette16.setBrush(QPalette.Active, QPalette.HighlightedText, brush4)
        palette16.setBrush(QPalette.Active, QPalette.Link, brush4)
        palette16.setBrush(QPalette.Active, QPalette.LinkVisited, brush7)
        palette16.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette16.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette16.setBrush(QPalette.Active, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette16.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette16.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette16.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette16.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette16.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette16.setBrush(QPalette.Inactive, QPalette.Mid, brush2)
        palette16.setBrush(QPalette.Inactive, QPalette.Text, brush5)
        palette16.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette16.setBrush(QPalette.Inactive, QPalette.ButtonText, brush5)
        palette16.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette16.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette16.setBrush(QPalette.Inactive, QPalette.Highlight, brush5)
        palette16.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush4)
        palette16.setBrush(QPalette.Inactive, QPalette.Link, brush4)
        palette16.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush7)
        palette16.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette16.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette16.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette16.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette16.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette16.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette16.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette16.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette16.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette16.setBrush(QPalette.Disabled, QPalette.Mid, brush2)
        palette16.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette16.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette16.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette16.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette16.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette16.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush4)
        palette16.setBrush(QPalette.Disabled, QPalette.Link, brush4)
        palette16.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush7)
        palette16.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush3)
        palette16.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette16.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette16.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.no_symbols_checkbox.setPalette(palette16)
        font5 = QFont()
        font5.setBold(False)
        font5.setStyleStrategy(QFont.PreferAntialias)
        self.no_symbols_checkbox.setFont(font5)
        PasswordGenerator.setCentralWidget(self.centralwidget)

        self.retranslateUi(PasswordGenerator)

        self.generate_button.setDefault(False)


        QMetaObject.connectSlotsByName(PasswordGenerator)
    # setupUi

    def retranslateUi(self, PasswordGenerator):
        PasswordGenerator.setWindowTitle(QCoreApplication.translate("PasswordGenerator", u"MainWindow", None))
        self.amount_label.setText(QCoreApplication.translate("PasswordGenerator", u"<html><head/><body><p><span style=\" font-size:12pt;\">Amount</span></p></body></html>", None))
        self.length_label.setText(QCoreApplication.translate("PasswordGenerator", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:700;\">Length</span></p></body></html>", None))
        self.generate_button.setText(QCoreApplication.translate("PasswordGenerator", u"Generate", None))
        self.exit_button.setText(QCoreApplication.translate("PasswordGenerator", u"Exit", None))
        self.clear_button.setText(QCoreApplication.translate("PasswordGenerator", u"Clear", None))
        self.addons_label.setText(QCoreApplication.translate("PasswordGenerator", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:700;\">Addons</span></p></body></html>", None))
        self.no_numbers_checkbox.setText(QCoreApplication.translate("PasswordGenerator", u"No Numbers", None))
        self.no_symbols_checkbox.setText(QCoreApplication.translate("PasswordGenerator", u"No Symbols", None))
    # retranslateUi

